"""empty message

Revision ID: 25da846ce4a2
Revises: 5e6b2dc97f1c
Create Date: 2021-12-05 19:38:27.701035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25da846ce4a2'
down_revision = '5e6b2dc97f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'name')
    # ### end Alembic commands ###
