"""empty message

Revision ID: 99fb1b1f50fb
Revises: cd40428e64f6
Create Date: 2021-12-05 14:46:55.924652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99fb1b1f50fb'
down_revision = 'cd40428e64f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'project', ['project_file'])
    op.add_column('user', sa.Column('realid', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('avatar_file', sa.String(length=85), nullable=True))
    op.create_unique_constraint(None, 'user', ['realid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'avatar_file')
    op.drop_column('user', 'realid')
    op.drop_constraint(None, 'project', type_='unique')
    # ### end Alembic commands ###
