"""empty message

Revision ID: c327be8bb8c8
Revises: 25da846ce4a2
Create Date: 2021-12-06 18:23:25.553525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c327be8bb8c8'
down_revision = '25da846ce4a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('communityid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'communityid')
    # ### end Alembic commands ###
